### ISSUE TITLE
Blacklisted tokens cannot be added to this contract

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/common-contract-deps#10]
There is no place in this contract where the `blacklistEscapeToken()` function is called, but it is an internal function...

I imagine you want to add it into the constructor and have a loop... this might need some solid tests written for it as well.

I LOVE this feature by the way, I might suggest that it be an `onlyEscapeHatchCallerOrOwner()`function so that it can allow selective decentralization, and that way it can avoid the loop that might need to be in the constructor.

Thoughts?

**Comment by adriamb** [comment]
Yes, this restricted functionality is a design decision.

`blacklistEscapeToken()` is designed to be internally called by child contracts mainly in constructor phase. This helps also that blacklisted tokens cannot be changed at runtime by the owner when contract is deployed ; for this reason `escapeBlacklist` is kept private and a public accessor `isTokenEscapable` is generated.

I cannot understand the loop thing, Griff.  Could you specify an concrete example of this use case, please?

**Comment by GriffGreen** [comment]
Thank you, the loop thing was to add multiple token contracts to the blacklist at once, but now i get the point... that the logic for adding to the black list must happen in the constructor for another child contract, that is a great way to go! I will add that info to the comments and close this issue ;-)
