### ISSUE TITLE
NPM Package needs to be updated

### ISSUE THREAD

**Issue by Alonski** [Giveth/common-contract-deps#23]
## Expected Behavior:
NPM Package for this repository is updated with the most recent changes.

## Current Behavior:
Currently the NPM Package is on an older version and thus has old contracts.
For example using SafeMath has Solidity warnings for not using pure functions even though this has already been fixed.

## What needs to be done:
Deploy NPM Package to latest version of this repository

**Comment by adriamb** [comment]
Thanks, done, uploaded 0.5.0 npm.

**Comment by Alonski** [comment]
Awesome thanks
